spring:
  application:
    name: executions-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
      data-source-properties:
        connectTimeout: 10
        socketTimeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: ${PORT:8080}